In [1]:
# Persent working directory!
import os
print(os.getcwd())

C:\Users\Sanje\Walmart_P6

In [2]:
# Installed requirments
# %pip install kagglehub
# %pip install sqlalchemy
# %pip install pymysql

In [3]:
# Download the dataset from kaggle
''' 
import kagglehub
import os

path = kagglehub.dataset_download(
    "najir0123/walmart-10k-sales-datasets"
)

print("Downloaded location:", path)
print("Files:", os.listdir(path))
'''

' \nimport kagglehub\nimport os\n\npath = kagglehub.dataset_download(\n    "najir0123/walmart-10k-sales-datasets"\n)\n\nprint("Downloaded location:", path)\nprint("Files:", os.listdir(path))\n'

In [4]:
# Moved the dataset to persent working directory or to the folder
'''
import shutil
import os

file_name = "Walmart.csv"

shutil.move(
    os.path.join(path, file_name),
    os.getcwd()
)'''

'\nimport shutil\nimport os\n\nfile_name = "Walmart.csv"\n\nshutil.move(\n    os.path.join(path, file_name),\n    os.getcwd()\n)'

# Data load and feature data.

In [24]:
# Importing dependencies
import pandas as pd
# MYSQL toolkit
import pymysql # work like SQL adapter
from sqlalchemy import create_engine

In [6]:
df = pd.read_csv('Walmart.csv',encoding_errors = 'ignore')

In [7]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [8]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [10]:
# To find value of duplicate
df.duplicated().sum()

np.int64(51)

In [11]:
df.drop_duplicates(inplace= True)
df.duplicated().sum()

np.int64(0)

In [12]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [13]:
# Dropping all rows with missing values
df.dropna(inplace=True)
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [14]:
df.shape

(9969, 11)

In [15]:
df['unit_price'] = df['unit_price'].str.replace('$','').astype(float)

In [16]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   object
 2   City            9969 non-null   object
 3   category        9969 non-null   object
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   object
 7   time            9969 non-null   object
 8   payment_method  9969 non-null   object
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 934.6+ KB

In [18]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='object')

In [19]:
df['total'] = df['unit_price']*df['quantity']
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [21]:
df.shape

(9969, 12)

In [22]:
df.to_csv('walmart_clean_data.csv',index=False)

In [25]:
engine_mysql = create_engine("mysql+pymysql://root:xxxxxxxxxx@localhost:3306/walmart_db")
try:
    engine_mysql
    print("Connected with SQL")
except:
    print("Unable to connect")

Connected with SQL

In [26]:
df.to_sql(name='walmart',con=engine_mysql,if_exists='append',index=False)

9969

In [ ]:
with engine_mysql.connect() as conn:
    result = conn.execute(text('SELECT * FROM walmart LIMIT 5'))

    for row in result:
        print(row)